In [ ]:
"""3"""
# f1- score
f1 = f1_score(y_true=y_test, y_pred=new_predictions, pos_label='2A')
print('F1: {}'.format(round(f1*100), 2))

In [20]:
# You can print or report the accuracy or use other metrics for evaluation
print(f"Random Forest Accuracy: {rf_accuracy}")
print(f"Extra Trees Accuracy: {et_accuracy}")
print(f"XGBoost Accuracy: {xgb_accuracy}")
# print(f"LightGBM Accuracy: {lgb_accuracy}")

#This code demonstrates the basic process of training the specified models and 
# evaluating their accuracy on the test set. You can adjust the evaluation metric and 
# other hyperparameters based on your specific use case and dataset.

Random Forest Accuracy: 0.016323633782824698
Extra Trees Accuracy: 0.0120652945351313
XGBoost Accuracy: 0.014904187366926898

In [19]:
# Evaluate the models' performance using a suitable metric, e.g., accuracy
rf_accuracy = accuracy_score(encoded_categorical_test_df, rf_predictions)
et_accuracy = accuracy_score(encoded_categorical_test_df, et_predictions)
xgb_accuracy = accuracy_score(encoded_categorical_test_df, xgb_predictions)
#lgb_accuracy = accuracy_score(test_y, lgb_predictions)

In [18]:

# Make predictions using each model on the test set
rf_predictions = rf_model.predict(scaled_numerical_test_df)
et_predictions = et_model.predict(scaled_numerical_test_df)
xgb_predictions = xgb_model.predict(scaled_numerical_test_df)
# lgb_predictions = lgb_model.predict(test_X)

In [17]:
"""
# Train the LightGBM Classifier
lgb_model = lgb.LGBMClassifier(random_state=random_seed)
encoded_categorical_train_df = encoded_categorical_train_df.stack().values
lgb_model.fit(scaled_numerical_train_df, encoded_categorical_train_df)

"""

'\n# Train the LightGBM Classifier\nlgb_model = lgb.LGBMClassifier(random_state=random_seed)\nencoded_categorical_train_df = encoded_categorical_train_df.stack().values\nlgb_model.fit(scaled_numerical_train_df, encoded_categorical_train_df)\n\n'

In [16]:
# Train the XGBoost Classifier
xgb_model = XGBClassifier(random_state=random_seed)
xgb_model.fit(scaled_numerical_train_df, encoded_categorical_train_df)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=1, ...)

In [15]:
# Train the Extra Trees Classifier
et_model = ExtraTreesClassifier(random_state=random_seed)
et_model.fit(scaled_numerical_train_df, encoded_categorical_train_df)

ExtraTreesClassifier(random_state=1)

In [14]:

# Train the Random Forest Classifier
rf_model = RandomForestClassifier(random_state=random_seed)
rf_model.fit(scaled_numerical_train_df, encoded_categorical_train_df)

RandomForestClassifier(random_state=1)

In [13]:
#Use scikit learn to train a random forest and extra trees classifier, and use xgboost and lightgbm to 
# train an extreme boosting model and a light gradient boosting model. Use random_state = 1 for 
# training all models and evaluate on the test set
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
import lightgbm as lgb
from sklearn.metrics import accuracy_score

# Set the random seed for reproducibility
random_seed = 1

In [12]:
# Combine scaled numerical and one-hot encoded categorical features into train and test set dataframes (use pd.concat)

# Combine scaled numerical and one-hot encoded categorical features for the training set
train_combined = pd.concat([scaled_numerical_train_df, encoded_categorical_train_df], axis=1)

# Combine scaled numerical and one-hot encoded categorical features for the test set
test_combined = pd.concat([scaled_numerical_test_df, encoded_categorical_test_df], axis=1)

In [11]:
# Split the categorical dataframe and numerical dataframe into an 80-20 train-test split with a random state of “1”

#split the data into training and testing sets
from sklearn.model_selection import train_test_split
encoded_categorical_train_df, encoded_categorical_test_df, scaled_numerical_train_df, scaled_numerical_test_df = train_test_split(categorical_encoded_df, numerical_scaled_df, test_size=0.2, random_state=1)

In [10]:
# The categorical features are one-hot encoded using OneHotEncoder(set sparse_output to false), 
# convert the output back to a dataframe and put back the column names.
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
categorical_encoded = encoder.fit_transform(categorical)

categorical_encoded_df = pd.DataFrame(categorical_encoded, columns=encoder.get_feature_names(input_features=categorical.columns))
categorical_encoded_df

C:\Users\SONOVGAD\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,gender_Female,gender_Male,SeniorCitizen_0,SeniorCitizen_1,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7039,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
7040,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
7041,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7042,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0

In [9]:
# The numerical features should be scaled using StandardScaler, convert the output back to a dataframe and 
# put back the column names.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numerical_scaled = scaler.fit_transform(numerical)
numerical_scaled_df = pd.DataFrame(numerical_scaled, columns=numerical.columns)
numerical_scaled_df

        tenure  MonthlyCharges  TotalCharges
0    -1.277445       -1.160323     -0.992611
1     0.066327       -0.259629     -0.172165
2    -1.236724       -0.362660     -0.958066
3     0.514251       -0.746535     -0.193672
4    -1.236724        0.197365     -0.938874
...        ...             ...           ...
7038 -0.340876        0.665992     -0.127605
7039  1.613701        1.277533      2.242606
7040 -0.870241       -1.168632     -0.852932
7041 -1.155283        0.320338     -0.870513
7042  1.369379        1.358961      2.013897

[7043 rows x 3 columns]

Feature engineering:

In [8]:
# Select these features:  categorical and numerical features
categorical_features = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService','OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies','Contract', 'PaperlessBilling', 'PaymentMethod']
numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
categorical = df[categorical_features]
numerical = df[numerical_features]

In [7]:
# Split the data into an 80-20 train-test split with a random state of “1”
# MORE PREPROCESSING
X = df.drop(columns = 'Churn')
y = df['Churn']


#split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
y_train.value_counts()

0    4113
1    1521
Name: Churn, dtype: int64

In [6]:
# Convert the 'Churn' column to binary values, where 'No' is mapped to 0 and 'Yes' is mapped to 1
df['Churn'] = df['Churn'].replace({'No': 0, 'Yes': 1})
df['Churn']

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [5]:
# preprocessing
# Perform initial data preparation by converting the 'TotalCharges' column to numeric values and 
# filling missing values with 0
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(value=0)
df['TotalCharges']

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [4]:
import pandas as pd
import numpy as np
# importing dataframe
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

Preprocessing: